SecAction "id:900000, phase:1, nolog, pass, t:none, setvar:tx.paranoia_level=1"

SecRule REQUEST_METHOD "@strei POST PUT PATCH" "id:100001,phase:1,pass,nolog,setvar:tx.allowed_methods=1"

SecRule ARGS|ARGS_NAMES|REQUEST_URI|REQUEST_HEADERS "@validateByteRange 1-255" "id:100002,phase:2,deny,status:400,msg:'Invalid character in request'"

SecRule ARGS|ARGS_NAMES|REQUEST_HEADERS|REQUEST_BODY "@rx (\{\$|\$\(|\`|\%\{)" "id:100003,phase:2,deny,status:403,msg:'Command Injection Attempt'"

SecRule ARGS|REQUEST_HEADERS|REQUEST_BODY "@rx (\\b(?:https?|ftp|file)://)" "id:100004,phase:2,deny,status:403,msg:'SSRF Attempt'"